site_url: https://smaragdiludus.github.io/
site_name: Smaragdi Ludus
site_author: Celebra Anser

theme:
   
   language: en
   name: "material"
   favicon: images/favicon_3.png
   #logo: images/favicon_3.png
   logo: images/favicon_totalwhite.png
   

   features:
      - navigation.instant
      - navigation.prune
      - navigation.tracking
      - navigation.tabs
      #- navigation.sections
      #- navigation.expand
      #- navigation.indexes
      - toc.follow
      #- toc.integrate
      - navigation.top

      - search.suggest
      - search.highlight
      - search.share

      - header.autohide
      - announce.dismiss

      - navigation.footer

   palette:
      # Light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: default
        accent: default
        toggle:
           icon: material/toggle-switch-off-outline
           name: Switch to dark mode

      # Dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: default
        accent: default
        toggle:
           icon: material/toggle-switch
           name: Switch to light mode


# Extensions
markdown_extensions:
   - footnotes
   - attr_list
   - tables
   - pymdownx.arithmatex:
        generic: true
   # - pymdownx.superfences
   # - pymdownx.details
   # - pymdownx.magiclink
   - pymdownx.tasklist:
        custom_checkbox: true
   - def_list
   - pymdownx.critic
   - pymdownx.caret
   - pymdownx.keys
   - pymdownx.mark
   - pymdownx.tilde
   - pymdownx.superfences:
        custom_fences:
           - name: mermaid
             class: mermaid
             format: !!python/name:pymdownx.superfences.fence_code_format

   - toc:
        permalink: true

extra: 
   consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

   #Rimuove logo Made with Material for MkDocs
   generator: false

   analytics:
      provider: google
      property: G-Q6ZCJHE3BS

   material:
      header:
         logo:
            href: false
   
   extra_css:
   - stylesheets/extra.css         
            

copyright: Copyright © 2022-2024 Smaragdi Ludus by Celebra Anser

plugins:
   - search
   - roamlinks
   - include_dir_to_nav
   #- blog
   #blog_dir: notes
   #archive: false
   #archive_toc: true
   #categories: false
   #pagination: false
   #pagination_per_page: 5
   #pagination_template: "$link_first ~2~ $link_last"
   #post_readtime: false

   - tags:
        tags_file: tags.md

extra_javascript:
   - javascripts/mathjax.js
   - https://polyfill.io/v3/polyfill.min.js?features=es6
   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
   - https://unpkg.com/mermaid/dist/mermaid.min.js

nav:
  - "index.md"
  - "info.md"
  - "tags.md"
  - readings: contents/readings
  - notes: contents/notes



  
