site_name: Smaragdi Ludus

theme:
   name: "material"

   favicon: images/favicon_2.png
   logo: images/favicon_totalwhite.png

   features:
      - navigation.instant
      - navigation.prune
      #- navigation.tabs
      #- navigation.sections
      #- navigation.expand
      #- navigation.indexes
      - toc.follow
      #- toc.integrate
      - navigation.top

      - search.suggest
      - search.highlight
      - search.share

      - header.autohide
      - announce.dismiss

      #- navigation.footer

   palette:
      # Light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: default
        accent: default
        toggle:
           icon: material/toggle-switch-off-outline
           name: Switch to dark mode

      # Dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: default
        accent: default
        toggle:
           icon: material/toggle-switch
           name: Switch to light mode

extra_css:
   - stylesheets/extra.css

# Extensions
markdown_extensions:
   - footnotes
   - attr_list

   - pymdownx.arithmatex:
        generic: true
   # - pymdownx.superfences
   # - pymdownx.details
   # - pymdownx.magiclink
   - pymdownx.tasklist:
        custom_checkbox: true
   - def_list
   - pymdownx.critic
   - pymdownx.caret
   - pymdownx.keys
   - pymdownx.mark
   - pymdownx.tilde
   - pymdownx.superfences:
        custom_fences:
           - name: mermaid
             class: mermaid
             format: !!python/name:pymdownx.superfences.fence_code_format

   - toc:
        permalink: true

extra:
   #Rimuove logo Made with Material for MkDocs
   generator: false

   analytics:
      provider: google
      property: G-Q6ZCJHE3BS

copyright: Copyright © 2022-2023 Smaragdi Ludus by Celebra Anser

plugins:
   - search
   - roamlinks
   - include_dir_to_nav
   - blog:
        blog_dir: notes
        archive: false
        categories: false
        pagination_per_page: 3
        #pagination: false
        #archive_toc: true

   - tags:
        tags_file: tags.md

extra_javascript:
   - javascripts/mathjax.js
   - https://polyfill.io/v3/polyfill.min.js?features=es6
   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
   - https://unpkg.com/mermaid/dist/mermaid.min.js

nav:
   - "index.md"
   - "info.md"
   #- notes: notes
   - "tags.md"
   - notes: "notes/index.md"
