name: ci

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repository
      - uses: actions/checkout@v3
        with:
          # Ignora le cartelle inutili per velocizzare il checkout
          fetch-depth: 1

      # 2. Setup Python
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # 3. Cache per pip
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4. Installazione pacchetti Python solo se cambiati
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Build del sito pulito
      - name: Build site
        run: mkdocs build --clean

      # 6. Deploy su GitHub Pages forzato
      - name: Deploy site
        run: mkdocs gh-deploy #--force
